engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/LineLength:
        enabled: true
        max: 99
      Rubocop/Style/TrailingWhitespace:
        enabled: false
      Rubocop/Style/RedundantReturn:
        enabled: false

  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- doc/**/*
